version: '2'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: swagger-editor
    environment:
      - 'SWAGGER_FILE=/tmp/src/main/resources/metav3-openapi.yaml'
    ports:
      - "80:8080"
    volumes:
      - ./:/tmp

