version: "3"

volumes:
  miniodata:

services:

  api:
    build:
      context: ..
      dockerfile: ./tapis-files/Dockerfile
    image: tapis-files
    volumes:
      - .:/api
    environment:
      - TAPIS_DB_USERNAME=dev
      - TAPIS_DB_PASSWORD=dev
      - TAPIS_DB_URL=jdbc:postgresql://postgres/dev
      - TAPIS_SKIP_JWT_VERIFY=true
    ports:
      - 8080:8080
      - 5005:5005
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/api/target/tapis-files.jar"]

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=user
      - MINIO_SECRET_KEY=password
    volumes:
      - miniodata:/data
    command: server /data