version: "3"

volumes:
  miniodata:

services:

  api:
    build:
      context: ..
      dockerfile: ./tapis-files/Dockerfile
    environment:
      - TAPIS_DB_NAME=dev
      - TAPIS_DB_PASSWORD=dev
      - TAPIS_DB_URL=jdbc:postgresql://postgres/dev


  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=user
      - MINIO_SECRET_KEY=password
    volumes:
      - miniodata:/data
    command: server /data